name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: install
        run: npm install

      - name: install cypress
        run: npm install -D cypress
        
      - name: Cypress run
        run: npx cypress run --browser chrome --browser firefox --spec="cypress/**/**/login*"

      - name: print me
        run: echo "I am here!"